# Dockerfile pour la production
FROM node:20

# Install Ghostscript
RUN apt-get update && apt-get install -y ghostscript

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install only production dependencies
RUN npm install

# Copy the rest of your application code
COPY . .

# Expose the port your app runs on
EXPOSE 3000

# Command to start your application
CMD ["npm", "start"]
